### ISSUE TITLE
ref. of the regulator

### ISSUE THREAD

**Issue by jorgeal94** [ABangingDonk/OpenHaldex32#1]
hi! can you share the reference of the current regulator used to convert 12v to 3.3v? I will try to make your pcb v2, I'm looking at the app also and i think i can help you to make one flutter app version, I will try and send to you to test if you want! thanks to share your work!

**Comment by ABangingDonk** [comment]
Hey, of course! Sorry for the delayed response...

The regulator I am using is this one:
https://www.ebay.co.uk/itm/254490668546

I'd build this into the board at some point but this will have to do for prototyping :)

**Comment by jorgeal94** [comment]
bought that one on aliex
https://es.aliexpress.com/item/4001309835430.html?spm=a2g0o.order_list.0.0.cf34194drHu1oW&gatewayAdapt=glo2esp
I think that´s the same
When I can test that I will propose you a regulator circuit to embed on the PCB. Thanks for reply!
